services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - bookmark-network
    # environment:
    #   - MONGO_URI=${MONGO_URI}
    #   - FLASK_ENV=${FLASK_ENV}

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    networks:
      - bookmark-network
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
    #   - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    restart: unless-stopped
    networks:
      - bookmark-network
    # environment:
    #   - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_EXPRESS_USER}
    #   - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_EXPRESS_PASSWORD}
    #   - ME_CONFIG_MONGODB_URL=${MONGO_URI}

volumes:
  mongo-data:

networks:
  bookmark-network:
